encyclopedia/urls.py
from django.urls import path
from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path('<str:title>', views.entry_page, name='entry_page'),
    path('search/', views.search, name='search'),
    path('new/', views.create_new_page, name='create_new_page'),
    path('edit/', views.edit_page, name='edit'),
    path('random/', views.random_page, name='random_page')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class NewSearchForm(forms.Form):
    def __init__( self, *args, **kwargs ):
        super(NewSearchForm, self).__init__( *args, **kwargs )
        self.fields['title'].label = ""
    title = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))


class NewPageForm(forms.Form):
    def __init__( self, *args, **kwargs ):
        super(NewPageForm, self).__init__( *args, **kwargs )
        self.fields['title'].label = ""
        self.fields['content'].label = ""

    title = forms.CharField(
        help_text="<p class='text-secondary'>Please refer to <a class='text-info' href = https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax> GitHub’s Markdown guide</a> for guidance on how to use markdown.</p>",
        widget=forms.TextInput(attrs={
            'placeholder':'Enter Title', 
            'class':'col-sm-11'})
        )

    content = forms.CharField( 
        widget=forms.Textarea(attrs={
            'placeholder':'Enter markdown content', 
            'class':'col-sm-11', 
            'style': 'height: 35em;'})
    )


class NewEditForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(NewEditForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = ""
    
    content = forms.CharField(
        help_text="<p class='text-secondary'>Please refer to <a class='text-info' href = https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax> GitHub’s Markdown guide</a> for guidance on how to use markdown.</p>",
        widget=forms.Textarea(attrs={
            'class': 'col-sm-11',
            'style': 'height: 35em;'
        })
    )

encyclopedia/views.py
import markdown 

from django.shortcuts import render
from random import choice
from . import forms
from . import util

form = forms.NewSearchForm()


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        'form': form
    })


def entry_page(request, title):
    if util.get_entry(title) is None: 
        return render(request, 'encyclopedia/error404.html', {
            'message': 'Page not Found'
        })
    md = markdown.Markdown()
    return render(request, 'encyclopedia/entry.html', {
        'title': title.capitalize(),
        'content': md.convert(util.get_entry(title)),
        'form': form
    })


def search(request):
    if request.method == 'GET':
        form = forms.NewSearchForm(request.GET)
        if form.is_valid():
            entries = util.list_entries()
            title = form.cleaned_data['title']
            results = [entry for entry in entries if title.lower() in entry.lower()]
            if len(results) == 1 and results[0].lower() == title.lower(): return entry_page(request, results[0])
            else: 
                return render(request, 'encyclopedia/search_results.html', {
                    'results': results,
                    'form': form,
                    'title': title
                })

def create_new_page(request):
    if request.method == 'POST':
        new_form = forms.NewPageForm(request.POST)
        if new_form.is_valid():
            title = new_form.cleaned_data['title'].capitalize()
            content = new_form.cleaned_data['content']
            entries = [entry.lower() for entry in util.list_entries()]
            if title.lower() in entries:
                return render(request, 'encyclopedia/error_already_exists.html', {
                    'message': 'Page Already Exists'
                })
            util.save_entry(title, content)
            return entry_page(request, title)
 
    return render(request, 'encyclopedia/new.html', {
            'form': form,
            'new_form': forms.NewPageForm()
        })


def edit_page(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        edit_form = forms.NewEditForm(request.POST)
        if edit_form.is_valid():
            content = edit_form.cleaned_data['content'].strip()
            util.save_entry(title, content)
            return entry_page(request, title)
    
    title = request.GET.get('edit')
    return render(request, 'encyclopedia/edit.html', {
        'form': form,
        'title': title,
        'edit_form': forms.NewEditForm({'content': util.get_entry(title)})
    })


def random_page(request):
    return entry_page(request, choice(util.list_entries()))

       

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %} {{ title }} - Edit {% endblock %}

{% block search %} {{ form }} {% endblock %}

{% block body %} 
<form class="text-left mb-3" action="{% url 'encyclopedia:edit' %}" method="POST">
    {% csrf_token %}
    {{ edit_form }}
    <br>
    <button type="submit" name="title" value="{{ title }}" class="btn btn-primary">Save Changes</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %} {{title}} - Wiki {% endblock %}


{% block search %}
{{ form }}
{% endblock %}


{% block body %}

{{ content|safe }}
<form action="{% url 'encyclopedia:edit' %}" method="GET" class="text-left mb-3">
    <button type="submit" name="edit" value="{{ title }}" class="btn btn-secondary">edit</button>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/error404.html
{% extends 'encyclopedia/error_layout.html' %}

{% block title %} Page not Found {% endblock %}

{% block message %} 
<h1>Error 404</h1>
<h2>{{ message }}</h2>
{% endblock %}

encyclopedia/templates/encyclopedia/error_already_exists.html
{% extends 'encyclopedia/error_layout.html' %}

{% block title %} Page Already Exists {% endblock %}

{% block message %}
<h1>Error</h1>
<h2>{{ message }}</h2> 
{% endblock %}

encyclopedia/templates/encyclopedia/error_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'encyclopedia/error404.css' %}">
    </head>
    <body>
        <header>
            {% block message %}{% endblock %}
            <a href="{% url 'encyclopedia:index' %}">Home</a>
            <hr>
        </header>
    </body>
</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block search %}
{{ form }}
{% endblock %}
{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry_page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    {% block search %}{% endblock %}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                    
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends 'encyclopedia/layout.html' %}

{% block title %} Create New Entry {% endblock %}

{% block search %}
{{ form }}
{% endblock %}

{% block body %}
<form class="text-left mb-3" action="{% url 'encyclopedia:create_new_page' %}" method="POST">
    {% csrf_token %}
    {{ new_form }}
    <br>
    <input type="submit" value="Save Entry" class="btn btn-primary">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends 'encyclopedia/layout.html' %}

{% block title %} {{ title }} - Search {% endblock %}

{% block search %} 
{{ form }}
{% endblock %}

{% block body %}
<ul>
    <h2>Showing results containing "<em>{{ title }}</em>"</h2>
    {% for result in results %}
        <li><a href="{% url 'encyclopedia:entry_page' result %}">{{ result }}</a> </li>
    {% empty %}
        <h4>No results found!</h4>
    {% endfor %}
</ul>
{% endblock %}